# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd88124a46050e6b2499a24030ca775c3706298db99f93d445beceb5afafa2510e801bc58a8dd885766933276373eda3ff35e1eecb56c6677ade492de8099e21

test:
  secret_key_base: 57ef3331c5f19db920b007e89baa2b6e1fecc538902b557e76d6e0163abe4ab2895240bf9b185b85b6a68142f4a2599e98ee80826c3f540d7e65999ebf350bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
